INSERT INTO roles (name, created_at) VALUES ('Testing', now());
INSERT INTO permissions(name, system_name, module_name)
VALUES ('Create animal', 'create_animals', 'Animals'),
       ('Edit animal', 'edit_animals', 'Animals'),
       ('Delete animal', 'delete_animals', 'Animals'),
       ('Create food', 'create_foods', 'Foods'),
       ('Edit food', 'edit_foods', 'Foods'),
       ('Delete food', 'delete_foods', 'Foods'),
       ('Create shopping', 'create_shopping', 'Shopping'),
       ('Edit shopping', 'edit_shopping', 'Shopping'),
       ('Delete shopping', 'delete_shopping', 'Shopping'),
       ('Create zone', 'create_zones', 'Zones'),
       ('Edit zone', 'edit_zones', 'Zones'),
       ('Delete zone', 'delete_zones', 'Zones'),
       ('Create employee', 'create_employees', 'Employees'),
       ('Edit employee', 'edit_employees', 'Employees'),
       ('Delete employee', 'delete_employees', 'Employees'),
       ('Create region', 'create_regions', 'Regions'),
       ('Edit region', 'edit_regions', 'Regions'),
       ('Delete region', 'delete_regions', 'Regions'),
       ('Create user', 'create_users', 'Users'),
       ('Edit user', 'edit_users', 'Users'),
       ('Delete user', 'delete_users', 'Users'),
       ('Create role', 'create_roles', 'Roles'),
       ('Edit role', 'edit_roles', 'Roles'),
       ('Delete role', 'delete_roles', 'Roles'),
       ('Create ticket', 'create_tickets', 'Tickets'),
       ('Edit ticket', 'edit_tickets', 'Tickets'),
       ('Delete ticket', 'delete_tickets', 'Tickets'),
       ('Create supplier', 'create_suppliers', 'Suppliers'),
       ('Edit supplier', 'edit_suppliers', 'Suppliers'),
       ('Delete supplier', 'delete_suppliers', 'Suppliers');